#' A wrapper around '\%dopar\%' to recover messages/warnings in GUI environments
#' 
#' A fifo connection is opened and all output from the forked processes is
#' written to a temp file. After all processes finish, the file is read, deleted
#' and its contents returned together with the result of the actual parallel
#' computation.
#'
#' @param obj  A foreach object like for regular \%dopar\% (see foreach package
#'             documentation)
#' @param expr An expression to be evaluated in parallel like for regular
#'             \%dopar\% (see foreach package documentation)
#'
#' @return A list with slots res for the actual result of the parallel
#'         computation and out for the output generated by the individual
#'         processes
#'
#' @examples
#' test <- function() {
#'   message("abc")
#'   warning("def")
#'   1:5 + 1:3
#' }
#' 
#' library(singleCellFeatures)
#' 
#' registerDoMC(cores=detectCores())
#' res <- foreach(1:10, .combine=rbind) %doparMC% test()
#' 
#' message(paste(res$out, collapse="\n"))
#' res$res
#' 
#' @export
'%doparMC%' <- function(obj, expr) {
  filename <- tempfile()
  con <- fifo(filename, "w+")
  assign(x='con', value=con, envir=.GlobalEnv)
  
  e <- foreach:::getDoPar()
  result <- e$fun(obj, substitute({
    warnLevel <- getOption("warn")
    options(warn=1)
    sink(file=con, append=TRUE, type="message")
    on.exit({
      sink(file=NULL, type="message")
      options(warn=warnLevel)
    })
    res <- eval(expr)
  }), parent.frame(), e$data)
  
  output <- readLines(con)
  on.exit({
    unlink(filename)
    close(con)
    rm(con, envir=.GlobalEnv)
  })
  return(list(res=result, out=output))  
}

#' @export
saveRDSMC <- function(object, file, threads=detectCores()-1) {
  message("using ", threads, " threads for compression.")
  #con <- pipe(paste0("xz -T", threads, " -9 -f > ", file), "wb")
  con <- pipe(paste0("pigz -p ", threads, " -9 -f > ", file), "wb")
  saveRDS(object, file = con)
  on.exit(if(exists("con")) close(con))
}

#' @export
readRDSMC <- function(file, threads=detectCores()) {
  #message("using ", threads, " threads for decompression.")
  #con <- pipe(paste0("xz -d -k -c -T", threads, " ", file))
  con <- pipe(paste0("pigz -d -k -c ", file))
  object <- readRDS(file = con)
  on.exit(if(exists("con")) close(con))
  return(object)
}